### ISSUE TITLE
HTML elements should be aligned

### ISSUE THREAD

**Issue by corinnekunze** [asdnc/Tribute-Page-Free-Code-Camp#3]
One thing we need to consider with all of our code is consistent spacing. It's important to keep our code legible. It's really important in HTML because it describes the hierarchy of what elements are nested.

Here's an example that is problematic right now:
```
<!DOCTYPE html>
<html>
  <head>
	  <script src="https://cdn.freecodecamp.org/testable-projects-fcc/v1/bundle.js">
	  </script>
      <link href="https://fonts.googleapis.com/css?family=Raleway" rel="stylesheet"> <!--Google Font import -->
      <link href="https://fonts.googleapis.com/css?family=Sedgwick+Ave" rel="stylesheet"> <!--Google Font import -->
	  <title>Ada Lovelace Tribute Page</title>
  </head>
```

This is confusing because it looks like the first `<script>` tag is more deeply nested than it actually is. This is how things look when they are correctly aligned:

```
<!DOCTYPE html>
<html>
  <head>
      <script src="https://cdn.freecodecamp.org/testable-projects-fcc/v1/bundle.js"></script>
      <link href="https://fonts.googleapis.com/css?family=Raleway" rel="stylesheet"> <!--Google Font import -->
      <link href="https://fonts.googleapis.com/css?family=Sedgwick+Ave" rel="stylesheet"> <!--Google Font import -->
      <title>Ada Lovelace Tribute Page</title>
  </head>
<! -- etc. rest of html below to follow this pattern -->
```

**Comment by asdnc** [comment]
That makes total sense and is one thing I need to keep an eye on.  I found this site, https://www.10bestdesign.com/dirtymarkup/ , to help.  I don't think it fixes everything but helps make sure I have all the open and closing tags.

**Comment by corinnekunze** [comment]
Much better @asdnc!

**Comment by asdnc** [comment]
Yay!!

Sent from Mail for Windows 10
