### ISSUE TITLE
Shouldn't have inline CSS in HTML

### ISSUE THREAD

**Issue by corinnekunze** [asdnc/Tribute-Page-Free-Code-Camp#4]
https://github.com/asdnc/Tribute-Page-Free-Code-Camp/blob/448c8ce86d32690926a6093d8847789585f7aa25/index.html#L28

As best practice - we shouldn't have any inline CSS inside our HTML files. This ensures we are keeping our concerns separate. For ex: CSS is for styling, HTML is only for markup.

You can use a css class or id here to encompass this style.

**Comment by asdnc** [comment]
This is great feedback.  Thank you!
