### ISSUE TITLE
Missing Javascript script tag to include custom javascript

### ISSUE THREAD

**Issue by corinnekunze** [asdnc/Tribute-Page-Free-Code-Camp#6]
Related this issue: https://github.com/asdnc/Tribute-Page-Free-Code-Camp/issues/1

I noticed we are including the script tag for the free code camp javascript at the top of the page but we aren't including any script tags to link to the custom javascript you've written (to be added in #1 issue).

This works on codepen cuz it's going to automatically embed the javascript on the page. But I think it's a good exercise to make the real link here. You should ideally be able to look at these project files on your computer, open the index.html file in your browser and have everything work the same as codepen.

**Comment by asdnc** [comment]
This one I'm not sure how to fix.  With FCC, the project does not require students to write any JS, and they include the script to run tests.  They do mention that code from https://cdn.freecodecamp.org/testable-projects-fcc/v1/bundle.js can be used to test in any environment.  Will this fix the issue?  I've added it.

**Comment by corinnekunze** [comment]
hi @asdnc - make sure not to close the issue until it is fixed. Having pull requests open also helps so you can link the issue to the pull request to see what work was done.

You can continue to load the https://cdn.freecodecamp.org/testable-projects-fcc/v1/bundle.js in the script tag via a cdn. But you also need to load your custom javascript file, similar to how you would for a CSS file. Ex:
```
<html>
  <body>
    My html content
    <script src="https://cdn.freecodecamp.org/testable-projects-fcc/v1/bundle.js"></script>
    <script src="my-javascript-file.js"></script> <!-- make sure that this file does not have the contents of bundle.js so you don't load the code twice -->
  </body>
</html>
```
